export const GET_MANAGER_BY_LOGIN_PASSWORD_REQUEST = 'GET_MANAGER_BY_LOGIN_PASSWORD_REQUEST';
export const GET_MANAGER_BY_LOGIN_PASSWORD_SUCCESS = 'GET_MANAGER_BY_LOGIN_PASSWORD_SUCCESS';
export const GET_CURRENT_MANAGER = 'GET_CURRENT_MANAGER';
