export const GET_HEAD_BY_LOGIN_PASSWORD_REQUEST = 'GET_HEAD_BY_LOGIN_PASSWORD_REQUEST';
export const GET_HEAD_BY_LOGIN_PASSWORD_SUCCESS = 'GET_HEAD_BY_LOGIN_PASSWORD_SUCCESS';
export const GET_CURRENT_HEAD = 'GET_CURRENT_HEAD';
