export const GET_MATERIAL_LIST_REQUEST = 'GET_MATERIAL_LIST_REQUEST';
export const GET_MATERIAL_LIST_SUCCESS = 'GET_MATERIAL_LIST_SUCCESS';
export const GET_MATERIAL_LIST_FAILURE = 'GET_MATERIAL_LIST_FAILURE';
