export const GET_ORDERS_OF_CUSTOMER_REQUEST = 'GET_ORDERS_OF_CUSTOMER_REQUEST';
export const GET_ORDERS_OF_CUSTOMER_SUCCESS = 'GET_ORDERS_OF_CUSTOMER_SUCCESS';
export const GET_ORDERS_OF_CUSTOMER_FAILURE = 'GET_ORDERS_OF_CUSTOMER_FAILURE';
