export const GET_CUSTOMER_ORDER_LIST_REQUEST = 'GET_CUSTOMER_ORDER_LIST_REQUEST';
export const GET_CUSTOMER_ORDER_LIST_SUCCESS = 'GET_CUSTOMER_ORDER_LIST_SUCCESS';
export const CLEAN_ORDER_LIST = 'CLEAN_ORDER_LIST';
// export const ADD_CUSTOMER_ORDER_SUCCESS = 'GET_CUSTOMER_ORDER_LIST_SUCCESS';
